name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-python@v6.3.0
        with:
          python-version: "3.12"
      - name: Run tests
        run: python -m unittest discover -s tests
      - name: Compile
        run: python -X pycache_prefix=build/pycache -m compileall src
